### ISSUE TITLE
Multiple runs and the work_flow_multi_run branch

### ISSUE THREAD

**Issue by Scaatis** [SpiNNakerManchester/sPyNNakerExternalDevicesPlugin#22]
I ran this test: [Single neuron live extraction example](https://gist.github.com/Scaatis/e10c3fd1247d87bded22)

It works correctly, extracting spikes from the first run. However, the second run doesn't start, but rather hangs at:
```
2015-12-08 16:53:32 INFO: *** Awaiting for a response from an external source to state its ready for the simulation to start ***
```

**Comment by rowleya** [comment]
It looks like either the receiver has to be reset on each run, or more simply, don’t do the notification protocol the second time run is called.  This could be an option (e.g. wait_for_notification_on_rerun).

**Comment by alan-stokes** [comment]
Howdi,

so this is because the spynnaker live spikes connection hadn’t been augmented for reset and rerun. Once I've fixed some stuff in this branch, ill look into it. Its worth noting that now we're moving away from pynn support and into our own specialized support, so we've got a bit more freedom.

This interface is hopefully going to be converted into the music interface, so getting it working now will gain us for the future.

Alan

**Comment by alan-stokes** [comment]
howdi, there is now a fix in a branch called malloc_sdram_from_host for the front_end_common.

This is because the work I've been doing has all been based ff the multi-run branch, which alas has not been merged into master yet (mainly due to the limitations that my new branches fix) 

Therefore if you want to use the fixes straight out, you'll need to shift to these modules and branches:

PACMAN:work_flow_multi_run
PyNN_Examples: work_flow_multi_run
SpiNNFrontEndCommon: malloc_sdram_from_host
SpiNNMachine: master
SpiNNMan: Heap_stuff
spynnaker: malloc_sdram_from_host
spynnakerExternalDevicesPlugin: work_flow_multi_run

alternatively, the commit which contains all the changes can be found here:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/commit/0d7487c8418661a9044060ed89c1dfb20d0d3f52
you could move over these changes and it would likely work (the rest of the changes don't touch these functions)

Interestingly, if your using a 4 chip board, these branches include fixes for the iobuf and therefore the machine wont crash over multiple executions without resetting. 

regards
Alan

**Comment by alan-stokes** [comment]
im going to close this issue, but feel free to reopen it if things screw up.

**Comment by Scaatis** [comment]
Working now.

> Interestingly, if your using a 4 chip board, these branches include fixes for the iobuf and therefore the machine wont crash over multiple executions without resetting.

Neat, I've actually been having that problem.
