### ISSUE TITLE
Retina (and SpikeSourceArray) edges always routing entire source spectrum

### ISSUE THREAD

**Issue by tophensen** [SpiNNakerManchester/sPyNNakerExternalDevicesPlugin#43]
Hi again, 
If I create a big population of IF neurons and project it to an array of smaller populations this creates many individual edges which are typically as wide as the address space of the neurons on the respective source subvertex. Although not optimal, because the target cores might receive packets which it does not care about, this is typically acceptable. 

For virtual cores/chips like the PushBotRetinaDevice, though, this leads to the horrible situation in which all spikes generated by the retina are sent to all cores which receive a projection from the retina - regardless of the size of this projection.

**Comment by tophensen** [comment]
Here's a testcase including report data which demonstrates the problem and shows that it is relevant for SpikeSourceArrays as well. 

[edge_case.zip](https://github.com/SpiNNakerManchester/sPyNNakerExternalDevicesPlugin/files/744604/edge_case.zip)

The quick fix would be to expose the retina as an array of populations representing individual pixel rows. A better fix would be, of course, to modify the routing logic.

**Comment by rowleya** [comment]
The solution to this is to allow some level of sub-population routing.  This could, for example, add multiple edges between the source and destination when the source is large enough, where each edge only routes a subset of the atoms.  This would require that the front-end would only add the appropriate edges to the graph.  

To take this to the extreme is to route each atom of the source population separately.  This could be done, but would rely upon a clever key allocation mechanism to ensure that the keys are compressible.

Note also that the routing would have to take account of things that go nowhere and cut them off correctly e.g. if you are using the retina and only want half the packets (e.g. the down-spikes), the up-spikes are still sent, so the routing table would have to include a stop-entry.  With the SpikeSourceArray, this is less of an issue since the spikes are core-sourced and so won't go anywhere without an initial entry on the source chip.

**Comment by alan-stokes** [comment]
Hi All,

The reason I avoided doing exactly that was due to the extra changes needed
by the mapping tools.

The vertex would need to allocate specific keys for the retina on each
edge, which is doable (thank you edge partition work from a year ago), but
dubious from the routing key generators, as it might not like allocating
certain blocks (need to ensure none overlapping) and that would be
difficult for the different key reps for different size retina input, as
there was vague memory that the polarity bit is not right next to the
neuron ids (could be wrong, been a while since i looked at this stuff).

The stop entry doesn't map at all to our tools to date, which means that
the routing table generator needs to treat it specially, which is a problem
from the generality of the mapping tools, which we try to maintain. Without
it though, you'd have packets just flying around, which would cause epic
issues.

to do it within the world we live in now, we'd need to have sink nodes that
are added once all the projections are put in, to replace the stop entry.
This might overload the router table though.......... difficult one to
solve without breaking other assumptions. or Dave Lesters router table
generator could be implemented which might solve this issue....... but
possibly cause other issues. Lovely multi dimensional optimisation problem
there.

if your going down the route of splitting the retina into 32768 machine
vertices (128 * 128 * 2), we'd need to up the number of cores supported on
a virtual chip. A virtual chip has 128 cores currently. There is a
interesting issue on how big the virtual chip cores should be, because on
top of the retina, you've got the motors, led, laser etc.  current
assumptions assumed 1:1 mapping of pop vertex to machine vertex for
external devices and therefore having 128 virtual devices coming from the
same spinnaker link seemed dubious. If we're to go to neurons.............
what number of cores do we need?? could be have a lazy generation for the
processors @rowley? whats the max before our router going into the virtual
chip would blow up? wouldn't that blow up after 18? which we've yet to face?

food for thought.

question: is this input overloading the reception cores? to get all your
retina neurons to fire would be a epic worse case scenario. if not, we're
trying to fix a none problem to begin with.

regards
Alan

**Comment by rowleya** [comment]
So to answer the second question first, the way of overloading of the cores is an important factor in how this is dealt with:
1) If the cores are being overloaded in reception of too many packets, some pre-core filtering of the packets is going to be essential.
1) If the cores are managing to receive the packets but then are being overloaded in the master population table lookup, that would also probably require some filtering before reaching the core.  
1) If the master population table lookup is OK, but the time taken to bring down empty rows is the issue, we have a designed solution (not yet implemented) where the master population table is extended to add more sub-population entries, indicating more deeply which ranges of entries are needed and which are not.

In order to filter the packets before the cores, there are many ways to achieve the same thing.  One thought is to allow routing to take place as it does now, and then filter back the packets later by adding extra routing table entries.  This could be added as a post-processing step, and so the algorithms can be left as they are now.

In terms of adding multiple virtual cores, there is no reason why we can't add as many virtual cores as you want.  The easy option is to make this lazy as you suggest, but with the maximum capped at sys.maxint.  This would then avoid creating a large memory data structure when not needed.

**Comment by tophensen** [comment]
I don't know in which way the cores are being overloaded - but I am pretty sure I can overload them in many ways. Below is an excerpt from a 12s run of an eDVS directly projected to a IF_curr_exp population. I have also attached the report directory of this run. The scenery was just SpiNNaker's blinking lights seen from the dark inside of our SpiNNaker-cabinet, so the packet load could become orders of magnitude higher - up to around half a million packets per second with a single eDVS. Fortunately, thanks to you gentlemen we can now use multiple spinnaker-link inputs - this is really cool! 
Those stop entries you are mentioning - couldn't these be represented by virtual chips again? I like the idea of back filtering the existing routes, but have no idea how hard it is to implement that. So for the time being I would rather pick the low hanging fruit and split the virtual chip into, e.g. 128 cores, each representing 1 column of pixels if that is possible. With the current protocol the least significant 15 bits of the retina packets are 1p +7x +7y. Thanks again for your awesome software and support!

> 2017-02-01 14:48:49 WARNING: The live packet gatherer has lost 28 packets which have p
[2017-02-01-14-47-48-342918.zip](https://github.com/SpiNNakerManchester/sPyNNakerExternalDevicesPlugin/files/744967/2017-02-01-14-47-48-342918.zip)
ayloads during its execution. Try increasing the machine time step or increasing the time scale factor. If you are running in real time, try reducing the number of vertices which are feeding this live packet gatherer
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:3570:3824 on 1, 1, 16 saturated 247 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:1020:1274 on 0, 1, 11 saturated 80 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:2295:2549 on 1, 1, 4 saturated 17 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:1530:1784 on 0, 0, 15 saturated 16 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:13515:13769 on 1, 0, 14 saturated 21 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The live packet gatherer has lost 28 packets which have payloads during its execution. Try increasing the machine time step or increasing the time scale factor. If you are running in real time, try reducing the number of vertices which are feeding this live packet gatherer
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:11475:11729 on 1, 0, 12 saturated 8 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:14280:14534 on 0, 0, 12 saturated 31 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:9435:9689 on 0, 0, 11 saturated 7 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:12750:13004 on 1, 1, 8 saturated 107 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The weights from the synapses for pop_1:3060:3314 on 1, 0, 16 saturated 31 times. If this causes issues you can increase the spikes_per_second and / or ring_buffer_sigma values located within the .spynnaker.cfg file.
> 2017-02-01 14:48:49 WARNING: The router on 0, 0 has dropped 16 multicast route packets. Try increasing the machine_time_step and/or the time scale factor or reducing the number of atoms per core.
> 2017-02-01 14:48:49 WARNING: The router on 0, 4 has default routed 415064 multicast packets, but the router table did not expect any default routed packets. This occurs where the router has no entry associated with the multi-cast key. Try investigating the keys allocated to the vertices and the router table entries for this chip.
> 2017-02-01 14:48:49 WARNING: The router on 1, 1 has dropped 106 multicast route packets. Try increasing the machine_time_step and/or the time scale factor or reducing the number of atoms per core.
> 2017-02-01 14:48:49 WARNING: The router on 2, 6 has default routed 415064 multicast packets, but the router table did not expect any default routed packets. This occurs where the router has no entry associated with the multi-cast key. Try investigating the keys allocated to the vertices and the router table entries for this chip.
> 2017-02-01 14:48:49 WARNING: The router on 4, 8 has default routed 415064 multicast packets, but the router table did not expect any default routed packets. This occurs where the router has no entry associated with the multi-cast key. Try investigating the keys allocated to the vertices and the router table entries for this chip.

**Comment by rowleya** [comment]
Looking at that output, there are two main issues:
1) The weights saturated periodically.  This is probably because the rate of packets from the retina is quite large.  The current workaround for this is to set the value of "spikes_per_second" in the [Simulation] section of your .spynnaker.cfg file (the default is 30).  This is used to estimate the spike rates of the populations in order to scale the weights so that their sum doesn't overflow.  If they do overflow, the rate was probably higher than expected.  That said, you might not worry too much about a bit of an overflow in the buffers.
1) There are some default routed multicast packets.  This implies that some packets are being sent with unexpected keys.  My suspicion here (from the script you sent) is that you have used the "polarity" setting of the retina to only direct half of the spikes.  This was what I was referring to when I mentioned that you might need routes to stop spikes that don't go anywhere in a previous message.  I may change the code so that you have to specify projections from both polarities, or else remove the option to select the polarity for the time being.
1) There are some additional dropped packets.  These could simply be packets that have wrapped around the machine and then been dropped, or could be from the extra packets being sent above.

None of the messages suggest that cores are actually being overloaded from receiving too many packets.  Thus I wouldn't worry about the filtering too much.

**Comment by tophensen** [comment]
You are right, Andrew.
1. The saturated weights are unimportant and fixable 
2. The default routed MC packets disappear when I enable merged polarity, as then all the retina packets are actually routed somewhere.
3. The additional dropped packets appear mainly at hot spots where all retina spikes appear, but also IF_curr_exp spikes are generated and sent to the live_packet_gather.

**Comment by tophensen** [comment]
If I present a more interesting stimulus, though, I can overload the machine in more interesting ways:
I get multiple of these:
> 2017-02-01 16:31:22 WARNING: A Timer tick callback was still executing when the next timer tick callback was fired off for pop_1:12495:12749 on 1, 0, 3, 5 times. This is a sign of the system being overloaded and therefore the results are likely incorrect.  Please increase the machine time step or time_scale_factor or decrease the number of neurons per core

and these:

> WARNING: The timer for pop_1:15045:15299 on 0, 1, 11 fell behind by up to 6 ticks. This is a sign of the system being overloaded and therefore the results are likely incorrect. Please increase the machine time step or time_scale_factor or decrease the number of neurons per core

and these:

> The callback queue for pop_1:14535:14789 on 0, 0, 12 overloaded on 5 occasions. This is often a sign that the system is running too quickly for the number of neurons per core.  Please increase the machine time step or time_scale_factor or decrease the number of neurons per core

and these:

> WARNING: The router on 1, 1 has dropped 83226 multicast route packets. Try increasing the machine_time_step and/or the time scale factor or reducing the number of atoms per core.

Moreover, in different trials, I could also crash the machine:
> 2017-02-01 16:22:49 INFO: Application started - waiting 12.1 seconds for it to stop
> 2017-02-01 16:23:06 ERROR: An error has occurred during simulation
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/SpiNNFrontEndCommon/spinn_front_end_common/interface/spinnaker_main_interface.py", line 1240, in _do_run
>     executor.execute_mapping()
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/PACMAN/pacman/executor/pacman_algorithm_executor.py", line 445, in execute_mapping
>     results = algorithm.call(self._internal_type_mapping)
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/PACMAN/pacman/executor/algorithm_classes/abstract_python_algorithm.py", line 44, in call
>     results = self.call_python(method_inputs)
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/PACMAN/pacman/executor/algorithm_classes/python_class_algorithm.py", line 57, in call_python
>     return method(**inputs)
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/front_end_common_application_runner.py", line 85, in __call__
>     time_threshold)
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/SpiNNFrontEndCommon/spinn_front_end_common/interface/interface_functions/front_end_common_application_runner.py", line 218, in wait_for_execution_to_complete
>     all_core_subsets, {CPUState.PAUSED, CPUState.FINISHED}, txrx)
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/SpiNNFrontEndCommon/spinn_front_end_common/utilities/helpful_functions.py", line 329, in get_cores_not_in_state
>     core_infos = txrx.get_cpu_information(all_core_subsets)
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/SpiNNMan/spinnman/transceiver.py", line 1104, in get_cpu_information
>     cpu_info = process.get_cpu_info(core_subsets)
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/SpiNNMan/spinnman/processes/get_cpu_info_process.py", line 45, in get_cpu_info
>     self.check_for_error()
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/SpiNNMan/spinnman/connections/scp_request_pipeline.py", line 190, in _do_retrieve
>     response.read_bytestring(raw_data, offset)
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/SpiNNMan/spinnman/messages/scp/abstract_messages/abstract_scp_response.py", line 39, in read_bytestring
>     self.read_data_bytestring(data, _SCP_DATA_OFFSET + offset)
> 2017-02-01 16:23:06 ERROR: File "/home/toph/spinn-dev-git_2017-01-27_10-38-40/dev/SpiNNMan/spinnman/messages/scp/impl/scp_read_memory_response.py", line 21, in read_data_bytestring
>     "Read", "CMD_READ", self._scp_response_header.result)
>

**Comment by rowleya** [comment]
The SpiNNaker machine is never going to be able to run every network in real-time; the design specifications were for up to 10Hz spike rates for neurons with 1000 inputs per neuron connected at 10%.  If you increase the spike rate enough it will therefore overload at real time, and it isn't very hard to do this.

The actual error is a bit more concerning.  Is this repeatable? Do you know if the machine you are using has been "blacklisted" (this is a process we use to mark cores as unavailable if they have known faults).?

**Comment by tophensen** [comment]
No machine is ever going to be able to run every network in real-time; But SpiNNaker is able to process our stereo-fusion network in real-time, even at input rates up to several 100,000 events per second - using ReverseIPTagMulticastSources (basically one SpikeSourceArray/LiveSpikeInjector per pixel column) that is. Here's 2 fans as seen by a stereo-dvs-pair and processed and fused into a 3d-representation live by SpiNNaker:

 ![fig5_2fan-eval_85mm](https://cloud.githubusercontent.com/assets/5727580/22545146/e89cdc8a-e937-11e6-9a09-cb3cc535a600.png)

Using populations that represent individual columns the traffic and computation was distributed nicely. It would be incredibly awesome to have sPyNNaker do such optimizations automatically, but for the time being it would already help if I could split up the retina population behind the spinnaker link. 
Wouldn't population views/assemblies be the right PyNN instrument for things like that? Is that feature planned for the coming release?

**Comment by rowleya** [comment]
I could be wrong, but I think that you can only create Projections between Populations, not between PopulationViews and Populations.  In any case, this only solves how you specify the connectivity, not how we actually implement it.  In the case of the retina population, we have a very specific additional issue which is that if you don't add routing entries for every key the retina sends, you will end up with packets flying around the machine!

I suspect here that that filtering back of unnecessary packets would be a good way to go with this; this means that once you have the places where you need to receive the spikes of any neuron in a population, you can then go back to the tables and modify entries or add entries to reduce the amount of traffic a core is receiving.

It is worth noting that we know of a general purpose algorithm, yet to be implemented, that works in exactly this way: everything is routed to everyone in a small number of entries, and then additional entries are used to reduce the traffic going to each core.  As we have yet to implement this, we are not sure whether it will work.  Some hybrid of the two approaches could be useful though.

**Comment by alan-stokes** [comment]
that general purpose algorithm being the Dave Lester one which i mentioned
previously with
"This might overload the router table though.......... difficult one to
solve without breaking other assumptions. or Dave Lesters router table
generator could be implemented which might solve this issue....... but
possibly cause other issues. Lovely multi dimensional optimisation problem
there."

As I mentioned then, that algorithm has not been tested apart from
hypothetical thought processes and so we don't really have a strong idea
how that would effect other cores / the routing tables / the router
bandwidth etc.

It is a worth while shot, and the good thing about spynnaker and our tools
is that its trival to change the router being used once you have the new
router. Can add that to the pile.

The impl of the pop views and assemblies that's currently awaiting review
reduces back down to populations, because merging random sets of atoms
broke a shed load of stuff below, and wasn't considered critical given we
could merge back to populations and map them fine.

what we could do is have a extra algorithm that adds these entries after
routing table generation, but you've got the issue that routing tables are
going to get compressed on the chip when that router compressor pull
request comes in. So we're going to have to adjust the work flow
management again to ensure it went router_table_gen -> add_stop_entries ->
do compression -> load if not on chip. tracking which neurons haven't got a
connection would be a rather computation intensive state, and its
likely going to boil down to if that chips router has enough entries after
compression to  filter and transport packets. If it doesn't, using more
routers is dubious, as it depends on the routing between retina and
receiving cores.

The difference between your SSA/SI version and the retina is that your
SSA's are likely spread over multiple chips (60 is 4 chips), and therefore
it has 4 routers and you've only split per column, so there's still
potentially surplus packets flying around, but not enough to overload your
reception cores. The retina is going into one router, so you've asking a
lot from that router. I am intrigued on how you got 60 spike injectors to
work, given that there's not that many tags on the entire machine for you
there. Id like to see that code if its ok.

This still boils down to being able to allocate a subset of the keys for
the retina for each retina core, and ensure they together cover the key
space without any gaps. Having looked at the push bot doc, its actually not
that bad. the polarity bit is right next to the neuron ids, its not like
the fpga retina format (see
http://spinnakermanchester.github.io/docs/spinn-app-8.pdf). This wouldn't
be too hard to deduce, but we'd need to augment the spinnaker machine cores
to be lazy as we'll need shed load more virtual cores.

can put this modification on the pile of things to do. Maybe a capo project?

regards
Alan

**Comment by dkfellows** [comment]
This repository no longer hosts relevant code.
